---
title: "eds-221-day3-tasks-forloop"
format: html
editor_options: 
  chunk_output_type: inline
---

read in packages
```{r}
library(tidyverse)
library(here)
library(janitor)
```

read in data
```{r}
# read in data
toolik_biochem <- read_csv(here::here("data", "2011_Kling_Akchem.csv")) %>% 
  clean_names()
toolik_biochem$p_h <- na_if(toolik_biochem$p_h, ".")

# subset for only variables we want, at only the site we want
inlet_biochem <- toolik_biochem %>% 
  subset(site %in% c("Toolik Inlet")) %>% 
  select(p_h, doc_u_m, tdn_u_m)

# change columns from chr to dbl
inlet_biochem$p_h <- as.numeric(inlet_biochem$p_h)
inlet_biochem$doc_u_m <- as.numeric(inlet_biochem$doc_u_m)
inlet_biochem$tdn_u_m <- as.numeric(inlet_biochem$tdn_u_m)

head(inlet_biochem)

# find the mean
mean_biochem <- vector(mode = "numeric", length = ncol(inlet_biochem))

# for loop to find the mean 
for (i in 2:ncol(inlet_biochem)) {
  mean <- mean(inlet_biochem[[i]], na.rm = TRUE)
  mean_biochem[i] <- mean
}
mean_biochem

# second way to do mean
apply(inlet_biochem, 2, mean, na.rm=TRUE)

# doesn't work why!!!
inlet_biochem %>%
  summarize(across(where(is.numeric), mean, na.rm = TRUE))
```

